language: java
jdk:
  - openjdk6
node_js:
  - 0.8
rvm:
  - 1.9.2
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - git submodule update --init --recursive &> /dev/null
  - npm install -g testacular@v0.5.8 &> /dev/null
  - gem install sass &> /dev/null
  - gem install compass &> /dev/null
install: /bin/true
script:  ./travis.sh